### ISSUE TITLE
segfault might be cause by giconhelper

### ISSUE THREAD

**Issue by xiangzhai** [AOSC-Dev/elsa-shell#6]
```
coredumpctl gdb
           PID: 27778 (elsa-shell)
           UID: 1000 (zhaixiang)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: 一 2015-07-06 11:08:07 CST (6min ago)
  Command Line: elsa-shell
    Executable: /usr/bin/elsa-shell
 Control Group: /user.slice/user-1000.slice/session-c6.scope
          Unit: session-c6.scope
         Slice: user-1000.slice
       Session: c6
     Owner UID: 1000 (zhaixiang)
       Boot ID: fd47a1242d954dc9b5c2f3bb6988aa0d
    Machine ID: a8be58a3b12246e7afe9010dcd4b0993
      Hostname: archlinux
      Coredump: /var/lib/systemd/coredump/core.elsa-shell.1000.fd47a1242d954dc9b5c2f3bb6988aa0d.27778.1436152087000000.lz4
       Message: Process 27778 (elsa-shell) of user 1000 dumped core.

GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/elsa-shell...done.
[New LWP 27778]
[New LWP 27935]
[New LWP 27809]
[New LWP 27808]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `elsa-shell'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f58580cb528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f58580cb528 in raise () at /usr/lib/libc.so.6
#1  0x00007f58580cc93a in abort () at /usr/lib/libc.so.6
#2  0x00007f5858935565 in g_assertion_message (domain=domain@entry=0x7f585b051c98 "Gtk", file=file@entry=0x7f585b085321 "gtkiconhelper.c", line=line@entry=759, func=func@entry=0x7f585b0853a0 <__func__.53576> "ensure_surface_for_gicon", message=message@entry=0xfd24a0 "code should not be reached") at gtestutils.c:2356
#3  0x00007f58589355da in g_assertion_message_expr (domain=domain@entry=0x7f585b051c98 "Gtk", file=file@entry=0x7f585b085321 "gtkiconhelper.c", line=line@entry=759, func=func@entry=0x7f585b0853a0 <__func__.53576> "ensure_surface_for_gicon", expr=expr@entry=0x0) at gtestutils.c:2371
#4  0x00007f585ae81fe0 in _gtk_icon_helper_ensure_surface (context=0x10d21d0 [GtkStyleContext], self=0x10bc1e0 [GtkIconHelper]) at gtkiconhelper.c:759
#5  0x00007f585ae81fe0 in _gtk_icon_helper_ensure_surface (self=0x10bc1e0 [GtkIconHelper], context=context@entry=0x10d21d0 [GtkStyleContext]) at gtkiconhelper.c:803
#6  0x00007f585ae8259e in _gtk_icon_helper_draw (self=<optimized out>, context=0x10d21d0 [GtkStyleContext], cr=0x188f110, x=0, y=3) at gtkiconhelper.c:1117
#7  0x00007f585ae966b5 in gtk_image_draw (widget=<optimized out>, cr=0x188f110)
    at gtkimage.c:1737
#8  0x00007f585aebcdb7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad67db0, instance=instance@entry=0x10b8cf0, args=args@entry=0x7ffe6ad67ea8, marshal_data=marshal_data@entry=0x7f585ae96440 <gtk_image_draw>, n_params=n_params@entry=1, param_types=0x87e430) at gtkmarshalers.c:130
#9  0x00007f585affff07 in gtk_widget_draw_marshallerv (closure=0x87e3c0, return_value=0x7ffe6ad67db0, instance=0x10b8cf0, args=0x7ffe6ad67ea8, marshal_data=0x7f585ae96440 <gtk_image_draw>, n_params=1, param_types=0x87e430) at gtkwidget.c:1097
#10 0x00007f5858decfd2 in _g_closure_invoke_va (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad67db0, instance=instance@entry=0x10b8cf0, args=args@entry=0x7ffe6ad67ea8, n_params=1, param_types=0x87e430) at gclosure.c:864
#11 0x00007f5858e06d99 in g_signal_emit_valist (instance=0x10b8cf0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe6ad67ea8) at gsignal.c:3246
---Type <return> to continue, or q <return> to quit---
#12 0x00007f5858e078b2 in g_signal_emit (instance=instance@entry=0x10b8cf0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3393
#13 0x00007f585b00e975 in _gtk_widget_draw_internal (widget=widget@entry=0x10b8cf0 [GtkImage], cr=cr@entry=0x188f110, clip_to_size=clip_to_size@entry=1, window=window@entry=0x18d62a0 [GdkX11Window]) at gtkwidget.c:6964
#14 0x00007f585b01052b in _gtk_widget_draw (window=0x18d62a0 [GdkX11Window], clip_to_size=1, cr=0x188f110, widget=0x10b8cf0 [GtkImage]) at gtkwidget.c:7151
#15 0x00007f585b01052b in _gtk_widget_draw (widget=widget@entry=0x10b8cf0 [GtkImage], cr=cr@entry=0x188f110) at gtkwidget.c:7142
#16 0x00007f585ae00781 in gtk_container_propagate_draw (container=container@entry=0xdd1740 [GtkEventBox], child=0x10b8cf0 [GtkImage], cr=cr@entry=0x188f110) at gtkcontainer.c:3704
#17 0x00007f585ae00892 in gtk_container_draw (widget=<optimized out>, cr=0x188f110)
    at gtkcontainer.c:3539
#18 0x00007f585ae42a19 in gtk_event_box_draw (widget=0xdd1740 [GtkEventBox], cr=0x188f110)
    at gtkeventbox.c:622
#19 0x00007f585aebcdb7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad682e0, instance=instance@entry=0xdd1740, args=args@entry=0x7ffe6ad683d8, marshal_data=marshal_data@entry=0x7f585ae429e0 <gtk_event_box_draw>, n_params=n_params@entry=1, param_types=0x87e430) at gtkmarshalers.c:130
#20 0x00007f585affff07 in gtk_widget_draw_marshallerv (closure=0x87e3c0, return_value=0x7ffe6ad682e0, instance=0xdd1740, args=0x7ffe6ad683d8, marshal_data=0x7f585ae429e0 <gtk_event_box_draw>, n_params=1, param_types=0x87e430) at gtkwidget.c:1097
#21 0x00007f5858decfd2 in _g_closure_invoke_va (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad682e0, instance=instance@entry=0xdd1740, args=args@entry=0x7ffe6ad683d8, n_params=1, param_types=0x87e430) at gclosure.c:864
#22 0x00007f5858e06d99 in g_signal_emit_valist (instance=0xdd1740, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe6ad683d8) at gsignal.c:3246
#23 0x00007f5858e078b2 in g_signal_emit (instance=instance@entry=0xdd1740, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3393
---Type <return> to continue, or q <return> to quit---
#24 0x00007f585b00e975 in _gtk_widget_draw_internal (widget=widget@entry=0xdd1740 [GtkEventBox], cr=cr@entry=0x188f110, clip_to_size=clip_to_size@entry=1, window=window@entry=0x18d62a0 [GdkX11Window]) at gtkwidget.c:6964
#25 0x00007f585b01017f in _gtk_widget_draw_windows (window=0x18d62a0 [GdkX11Window], clip_to_size=1, cr=0x188f110, widget=0xdd1740 [GtkEventBox]) at gtkwidget.c:6942
#26 0x00007f585b01017f in _gtk_widget_draw_windows (window=window@entry=0x18d62a0 [GdkX11Window], cr=cr@entry=0x188f110, window_x=window_x@entry=0, window_y=window_y@entry=0)
    at gtkwidget.c:7065
#27 0x00007f585b010401 in _gtk_widget_draw (widget=widget@entry=0xdd1740 [GtkEventBox], cr=cr@entry=0x188f110) at gtkwidget.c:7136
#28 0x00007f585ae00781 in gtk_container_propagate_draw (container=container@entry=0x10b8900 [GtkBox], child=0xdd1740 [GtkEventBox], cr=cr@entry=0x188f110) at gtkcontainer.c:3704
#29 0x00007f585ae00892 in gtk_container_draw (widget=<optimized out>, cr=0x188f110)
    at gtkcontainer.c:3539
#30 0x00007f585adb49bf in gtk_box_draw (widget=0x10b8900 [GtkBox], cr=0x188f110) at gtkbox.c:447
#31 0x00007f585aebcdb7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad688a0, instance=instance@entry=0x10b8900, args=args@entry=0x7ffe6ad68998, marshal_data=marshal_data@entry=0x7f585adb4930 <gtk_box_draw>, n_params=n_params@entry=1, param_types=0x87e430) at gtkmarshalers.c:130
#32 0x00007f585affff07 in gtk_widget_draw_marshallerv (closure=0x87e3c0, return_value=0x7ffe6ad688a0, instance=0x10b8900, args=0x7ffe6ad68998, marshal_data=0x7f585adb4930 <gtk_box_draw>, n_params=1, param_types=0x87e430) at gtkwidget.c:1097
#33 0x00007f5858decfd2 in _g_closure_invoke_va (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad688a0, instance=instance@entry=0x10b8900, args=args@entry=0x7ffe6ad68998, n_params=1, param_types=0x87e430) at gclosure.c:864
#34 0x00007f5858e06d99 in g_signal_emit_valist (instance=0x10b8900, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe6ad68998) at gsignal.c:3246
#35 0x00007f5858e078b2 in g_signal_emit (instance=instance@entry=0x10b8900, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3393
---Type <return> to continue, or q <return> to quit---
#36 0x00007f585b00e975 in _gtk_widget_draw_internal (widget=widget@entry=0x10b8900 [GtkBox], cr=cr@entry=0x188f110, clip_to_size=clip_to_size@entry=1, window=window@entry=0x10b8d20 [GdkX11Window]) at gtkwidget.c:6964
#37 0x00007f585b01052b in _gtk_widget_draw (window=0x10b8d20 [GdkX11Window], clip_to_size=1, cr=0x188f110, widget=0x10b8900 [GtkBox]) at gtkwidget.c:7151
#38 0x00007f585b01052b in _gtk_widget_draw (widget=widget@entry=0x10b8900 [GtkBox], cr=cr@entry=0x188f110) at gtkwidget.c:7142
#39 0x00007f585ae00781 in gtk_container_propagate_draw (container=container@entry=0xce4510 [GtkBox], child=0x10b8900 [GtkBox], cr=cr@entry=0x188f110) at gtkcontainer.c:3704
#40 0x00007f585ae00892 in gtk_container_draw (widget=<optimized out>, cr=0x188f110)
    at gtkcontainer.c:3539
#41 0x00007f585adb49bf in gtk_box_draw (widget=0xce4510 [GtkBox], cr=0x188f110) at gtkbox.c:447
#42 0x00007f585aebcdb7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad68dd0, instance=instance@entry=0xce4510, args=args@entry=0x7ffe6ad68ec8, marshal_data=marshal_data@entry=0x7f585adb4930 <gtk_box_draw>, n_params=n_params@entry=1, param_types=0x87e430) at gtkmarshalers.c:130
#43 0x00007f585affff07 in gtk_widget_draw_marshallerv (closure=0x87e3c0, return_value=0x7ffe6ad68dd0, instance=0xce4510, args=0x7ffe6ad68ec8, marshal_data=0x7f585adb4930 <gtk_box_draw>, n_params=1, param_types=0x87e430) at gtkwidget.c:1097
#44 0x00007f5858decfd2 in _g_closure_invoke_va (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad68dd0, instance=instance@entry=0xce4510, args=args@entry=0x7ffe6ad68ec8, n_params=1, param_types=0x87e430) at gclosure.c:864
#45 0x00007f5858e06d99 in g_signal_emit_valist (instance=0xce4510, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe6ad68ec8) at gsignal.c:3246
#46 0x00007f5858e078b2 in g_signal_emit (instance=instance@entry=0xce4510, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3393
#47 0x00007f585b00e975 in _gtk_widget_draw_internal (widget=widget@entry=0xce4510 [GtkBox], cr=cr@entry=0x188f110, clip_to_size=clip_to_size@entry=1, window=window@entry=0x10b8d20 [GdkX11Window]) at gtkwidget.c:6964
---Type <return> to continue, or q <return> to quit---
#48 0x00007f585b01052b in _gtk_widget_draw (window=0x10b8d20 [GdkX11Window], clip_to_size=1, cr=0x188f110, widget=0xce4510 [GtkBox]) at gtkwidget.c:7151
#49 0x00007f585b01052b in _gtk_widget_draw (widget=widget@entry=0xce4510 [GtkBox], cr=cr@entry=0x188f110) at gtkwidget.c:7142
#50 0x00007f585ae00781 in gtk_container_propagate_draw (container=container@entry=0xcee240 [GtkWindow], child=0xce4510 [GtkBox], cr=cr@entry=0x188f110) at gtkcontainer.c:3704
#51 0x00007f585ae00892 in gtk_container_draw (widget=<optimized out>, cr=0x188f110)
    at gtkcontainer.c:3539
#52 0x00007f585b01e914 in gtk_window_draw (widget=0xcee240 [GtkWindow], cr=0x188f110)
    at gtkwindow.c:9759
#53 0x00007f585aebcdb7 in _gtk_marshal_BOOLEAN__BOXEDv (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad69320, instance=instance@entry=0xcee240, args=args@entry=0x7ffe6ad69418, marshal_data=marshal_data@entry=0x7f585b01e880 <gtk_window_draw>, n_params=n_params@entry=1, param_types=0x87e430) at gtkmarshalers.c:130
#54 0x00007f585affff07 in gtk_widget_draw_marshallerv (closure=0x87e3c0, return_value=0x7ffe6ad69320, instance=0xcee240, args=0x7ffe6ad69418, marshal_data=0x7f585b01e880 <gtk_window_draw>, n_params=1, param_types=0x87e430) at gtkwidget.c:1097
#55 0x00007f5858ded084 in _g_closure_invoke_va (closure=closure@entry=0x87e3c0, return_value=return_value@entry=0x7ffe6ad69320, instance=instance@entry=0xcee240, args=args@entry=0x7ffe6ad69418, n_params=<optimized out>, param_types=0x87e430) at gclosure.c:864
#56 0x00007f5858e06d99 in g_signal_emit_valist (instance=0xcee240, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe6ad69418) at gsignal.c:3246
#57 0x00007f5858e078b2 in g_signal_emit (instance=instance@entry=0xcee240, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3393
#58 0x00007f585b00e975 in _gtk_widget_draw_internal (widget=widget@entry=0xcee240 [GtkWindow], cr=cr@entry=0x188f110, clip_to_size=clip_to_size@entry=1, window=window@entry=0x10b8d20 [GdkX11Window]) at gtkwidget.c:6964
#59 0x00007f585b01017f in _gtk_widget_draw_windows (window=0x10b8d20 [GdkX11Window], clip_to_size=1, cr=0x188f110, widget=0xcee240 [GtkWindow]) at gtkwidget.c:6942
---Type <return> to continue, or q <return> to quit---
#60 0x00007f585b01017f in _gtk_widget_draw_windows (window=window@entry=0x10b8d20 [GdkX11Window], cr=cr@entry=0x188f110, window_x=window_x@entry=0, window_y=window_y@entry=0)
    at gtkwidget.c:7065
#61 0x00007f585b010401 in _gtk_widget_draw (widget=widget@entry=0xcee240 [GtkWindow], cr=cr@entry=0x188f110) at gtkwidget.c:7136
#62 0x00007f585b01073b in gtk_widget_send_expose (widget=widget@entry=0xcee240 [GtkWindow], event=event@entry=0x7ffe6ad696d0) at gtkwidget.c:7613
#63 0x00007f585aebbcb0 in gtk_main_do_event (event=0x7ffe6ad696d0) at gtkmain.c:1673
#64 0x00007f5859c21d42 in _gdk_window_process_updates_recurse_helper (window=0x10b8d20 [GdkX11Window], expose_region=<optimized out>) at gdkwindow.c:3556
#65 0x00007f5859c22dec in gdk_window_process_updates_internal (window=0x10b8d20 [GdkX11Window])
    at gdkwindow.c:3681
#66 0x00007f5859c22fa3 in gdk_window_process_updates_with_mode (window=<optimized out>, recurse_mode=<optimized out>) at gdkwindow.c:3882
#67 0x00007f5858ded084 in _g_closure_invoke_va (closure=closure@entry=0x11a9190, return_value=return_value@entry=0x0, instance=instance@entry=0xcec310, args=args@entry=0x7ffe6ad699e0, n_params=<optimized out>, param_types=0x0) at gclosure.c:864
#68 0x00007f5858e07261 in g_signal_emit_valist (instance=instance@entry=0xcec310, signal_id=signal_id@entry=141, detail=detail@entry=0, var_args=var_args@entry=0x7ffe6ad699e0) at gsignal.c:3246
#69 0x00007f5858e07d28 in g_signal_emit_by_name (instance=0xcec310, detailed_signal=detailed_signal@entry=0x7f5859c825a7 "paint") at gsignal.c:3433
#70 0x00007f5859c1c134 in gdk_frame_clock_paint_idle (data=<optimized out>)
    at gdkframeclockidle.c:430
#71 0x00007f5859c0b698 in gdk_threads_dispatch (data=0x1a3ffa0, 
    data@entry=<error reading variable: value has been optimized out>) at gdk.c:719
#72 0x00007f5858910273 in g_timeout_dispatch (source=0x7f583c00c5e0, callback=<optimized out>, user_data=<optimized out>) at gmain.c:4545
#73 0x00007f585890f83a in g_main_context_dispatch (context=0x8a3440) at gmain.c:3122
#74 0x00007f585890f83a in g_main_context_dispatch (context=context@entry=0x8a3440)
---Type <return> to continue, or q <return> to quit---
    at gmain.c:3737
#75 0x00007f585890fbb8 in g_main_context_iterate (context=0x8a3440, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3808
#76 0x00007f585890fed2 in g_main_loop_run (loop=0x1391e60) at gmain.c:4002
#77 0x00007f585aebb0f5 in gtk_main () at gtkmain.c:1219
#78 0x000000000040cc2d in main (argc=1, argv=0x7ffe6ad69dc8) at main.c:114
```

**Comment by xiangzhai** [comment]
very difficult to reproduce ...
